services:
  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    restart: always

  api:
    build: .
    container_name: django_app
    ports:
      - 8000:8000
    volumes:
      - ./images:/app/media/images
    depends_on:
      - mariadb

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true